## The name of the environment matching the repository name

name: suvel
## I prefer conda-forge packages for my projects
channels:
- conda-forge
- defaults
## Start with Python and include everything you need
dependencies:
- python=3.10.11
- numpy
- matplotlib
- pip
- keras
- tensorflow
- scikit-learn